Network:
  # Possible bustypes:
  #   - socketcan: to use native socketcan driver. (on Linux)
  #   - pcan: to used PEAK CAN intercase. (You should have the PCANBasic.dll)
  bustype: "socketcan"
  # Possible channels:
  #   - can0: use with socketcan
  #   - PCAN_USBBUS1: use with pcan
  channel: "can0"
  bitrate: 500000
# Possible jobs:
#   - log: to log to the console
#   - publish: to publish through MQTT
Job: "log"
# CAN Message IDs to log
CAN_MESSAGES: [1, 2, 3, 4, 5, 6, 7, 8, 9, 124, 155, 245]
LOG_PERIOD: 0.1
SAVE_PERIOD: 10
