OBD:
  ID: "avl_obd_tracker1"
  # Possible jobs:
  #   - log: to log to the console
  #   - publish: to publish through MQTT
  job: "log"
  messages:
    [
      "FUEL_STATUS",
      "ENGINE_LOAD",
      "COOLANT_TEMP",
      "RPM",
      "SPEED",
      "RUN_TIME",
      "THROTTLE_POS",
      "FUEL_LEVEL",
      "FUEL_TYPE",
    ]
